const RollsActionTypes = {
  FETCH_ROLLS_START: "FETCH_ROLLS_START",
  FETCH_ROLLS_SUCCESS: "FETCH_ROLLS_SUCCESS",
  PUSH_ROLL_START: "PUSH_ROLL_START",
  PUSH_ROLL_SUCCESS: "PUSH_ROLL_SUCCESS",
  ROLLS_FAILURE: "ROLLS_FAILURE"
};

export default RollsActionTypes;
